### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by msciwoj1** [andre-juan/dicke_states_preparation#1]
Hello, the code looks really nice, I was looking for an implementation of the Dicke states in qiskit (from this paper: https://arxiv.org/pdf/2207.09998 by the same authors but this is still good). 

However, your repo has no licence which means legally noone is able to use the code. Could you please add one? https://choosealicense.com/no-permission/

Your hope to add this to qiskit, which is under Apache License 2.0, suggests to me this would also be a good licence for you, but you did not include any.

**Comment by andre-juan** [comment]
Hi!

I'm glad you're interested in using the code! I just added Apache License 2.0.

Thanks
